<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyTitle>PotionSwapper</AssemblyTitle>
    <AssemblyName>PotionSwapper</AssemblyName>
    <RootNamespace>PotionSwapper</RootNamespace>
    <Authors>i-wrote-this-myself</Authors>
    <Version>7.55.15.32</Version>
    <Description>A Dalamud plugin for FFXIV.</Description>
    <Platforms>x64</Platforms>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\x64\$(Configuration)\</OutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Nullable>enable</Nullable>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="DalamudPackager" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="PotionSwapper.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dalamud">
      <HintPath>/home/yseult/.xlcore/dalamud/Hooks/dev/Dalamud.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Dalamud.Bindings.ImGui">
      <HintPath>/home/yseult/.xlcore/dalamud/Hooks/dev/Dalamud.Bindings.ImGui.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ImGuiScene">
      <HintPath>/home/yseult/.xlcore/dalamud/Hooks/dev/ImGuiScene.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Lumina">
      <HintPath>/home/yseult/.xlcore/dalamud/Hooks/dev/Lumina.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>/home/yseult/.xlcore/dalamud/Hooks/dev/Lumina.Excel.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>/home/yseult/.xlcore/dalamud/Hooks/dev/Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FFXIVClientStructs">
      <HintPath>/home/yseult/.xlcore/dalamud/Hooks/dev/FFXIVClientStructs.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="InteropGenerator.Runtime">
      <HintPath>/home/yseult/.xlcore/dalamud/Hooks/dev/InteropGenerator.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
